pipeline {
    /* insert Declarative Pipeline here */
    agent any

    stages {
        stage('Preparation') { // for display purposes
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/wayne07/JTubeDownloaderFx.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                withMaven(maven : 'M3') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                withMaven(maven : 'M3') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}