#!groovy​
//# https://jenkins.io/doc/book/pipeline/
pipeline {
    /* insert Declarative Pipeline here */
    agent any

    environment {
        def gradleHome = ""
        def JAVA_HOME = "/opt/java/jdk1.8.0_162"
    }

    stages {
        stage('Clone sources') { // for display purposes
            steps {
                // Get some code from a GitHub repository
                dir('jtube') {
                    git url: 'https://github.com/wayne07/JTubeDownloaderFx.git'
                }
                dir('jenkinsJobs') {
                    git url: 'https://github.com/wayne07/jenkins-jobs.git'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'env'
#                withEnv(['JAVA_HOME="/opt/java/jdk1.8.0_162"']) {
                    // some block
                    sh './jtube/gradlew build'
#                }
//                buildInfo = rtGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}